[[main]]
name = "Home"
identifier = "home"
weight = 100
url = "/"

[[main]]
name = "About"
weight = 200
identifier = "about"
url = "/about/"

[[main]]
name = "Categories"
weight = 300
identifier = "categories"
url = "/categories/"

[[main]]
name = "Tags"
weight = 400
identifier = "tags"
url = "/tags/"
